parameters:
- name: environment
  type: string
- name: apiName
  displayName: Target API Name (case sensitive)
  type: string
- name: templatePath
  displayName: Storage Account relative template path
  type: string
- name: parameterFileName
  displayName: ARM Template Parameter filename
  type: string
- name: jobVariablesPath
  type: string

jobs:
  - deployment: deployApim
    environment: ${{ parameters.apiName }}-${{ parameters.environment }}
    displayName: Deploy APIM Template
    pool:
      vmImage: ubuntu-16.04
    variables:
      - template: ${{ parameters.jobVariablesPath }}
      - name: APIM_NAME
        value: ${{ variables.apimName }}
      - name: APIM_RESOURCE_GROUP
        value: ${{ variables.resourceGroupName }}
      - name: API_NAME
        value: ${{ parameters.apiName }}
      - name: STORAGE_ACCOUNT
        value: ${{ variables.storageName }}
      - name: STORAGE_RESOURCE_GROUP
        value: ${{ variables.resourceGroupName }}
      - name: CONTAINER
        value: ${{ variables.containerName }}
      - name: REMOTE_TEMPLATE_PATH
        value: ${{ parameters.templatePath }}
      - name: LOCAL_TEMPLATE_DIRECTORY
        value: $(Pipeline.Workspace)/Templates
      - name: PARAMETER_FILE_NAME
        value: ${{ parameters.parameterFileName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
          - task: AzureCLI@2
            displayName: Azure CLI - Storage Account Upload
            inputs:
              azureSubscription: ${{ variables.azsubscription }}
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: $(Pipeline.Workspace)/Scripts/apim-api-upload.sh
          - task: AzureCLI@2
            displayName: Azure CLI - Deploy APIM Template
            inputs:
              azureSubscription: ${{ variables.azSubscription }}
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: $(Pipeline.Workspace)/Scripts/apim-api-deploy.sh