parameters:
  - name: apiName
    displayName: Target API Name (case sensitive)
    type: string
  - name: templatePath
    displayName: Storage Account relative template path
    type: string
  - name: parameterFileName
    displayName: ARM Template Parameter filename
    type: string

variables:
 - template: variables.yml

# resources:
#   repositories:
#     - repository: tools
#       type: github
#       name: mrsmitty/apim-devops
#       ref: refs/heads/users/ps/extends
#       endpoint: Integration

stages:
- stage: development
  dependsOn: ${{ parameters.dependsOn }}
  displayName : ${{ value.name }}
  jobs:
  - template: job-apim-api-deploy.yml
    parameters:
      environment: development
      apiName: ${{ parameters.apiName }}
      parameterFileName: ${{ parameters.parameterFileName }}
  