parameters:
  - name: apiName
    displayName: Target API Name (case sensitive)
    type: string
  - name: storageAccountName
    displayName: Storage Account ARM Templates
    type: string
  - name: storageAccountResourceGroupName
    displayName: Storage Account Resource Group
    type: string
  - name: containerName
    displayName: Storage Account Container ARM Tempaltes
    type: string
  - name: templatePath
    displayName: Storage Account relative template path
    type: string
  - name: localTemplateDirectory
    displayName: Local Template Directory
    type: string
  - name: azSubscription
    type: string
variables:
 - template: variables.yml

# resources:
#   repositories:
#     - repository: tools
#       type: github
#       name: mrsmitty/apim-devops
#       ref: refs/heads/main
#       endpoint: Integration

stages:    
- stage: uploadStorageTemplates
  displayName : Upload API ARM Templates
  jobs:
    - job:
      displayName: Storage Account Upload
      pool:
        vmImage: ubuntu-16.04
      variables:
        - name: API_NAME
          value: ${{ parameters.apiName }}
        - name: STORAGE_ACCOUNT
          value: ${{ variables.environments[0].storageName }}
        - name: STORAGE_RESOURCE_GROUP
          value: ${{ variables.environments[0].resourceGroupName }}
        - name: CONTAINER
          value: ${{ variables.containerName }}
        - name: REMOTE_TEMPLATE_PATH
          value: ${{ parameters.templatePath }}
        - name: LOCAL_TEMPLATE_DIRECTORY
          value: ${{ parameters.localTemplateDirectory }}
      steps:
      - task: AzureCLI@2
        displayName: Azure CLI - Storage Account Upload
        inputs:
          azureSubscription: ${{ parameters.azsubscription }}
          scriptType: bash
          scriptLocation: scriptPath
          scriptPath: $(System.DefaultWorkingDirectory)/pipeline/scripts/apim-api-upload.sh
          
      - publish: $(System.DefaultWorkingDirectory)/pipeline/scripts/apim-api-deploy.sh
        artifact: Scripts
      - publish: $(System.DefaultWorkingDirectory)/api/${{ parameters.apiName }}
        artifact: Templates