parameters:
  - name: apiName
    displayName: Target API Name (case sensitive)
    type: string
  - name: templatePath
    displayName: Storage Account relative template path
    type: string
  - name: parameterFileName
    displayName: ARM Template Parameter filename
    type: string

variables:
 - template: variables.yml

# resources:
#   repositories:
#     - repository: tools
#       type: github
#       name: mrsmitty/apim-devops
#       ref: refs/heads/users/ps/extends
#       endpoint: Integration

stages:
- stage: staging
  displayName: Stage Scripts and Templates
  jobs:
  - job: stageArmTemplates
    pool:
      vmImage: ubuntu-latest
    steps:
    - publish: $(System.DefaultWorkingDirectory)/pipeline/scripts/apim-api-deploy.sh
      artifact: Scripts
    - publish: $(System.DefaultWorkingDirectory)/api/${{ parameters.apiName }}
      artifact: Templates

- stage: development
  dependsOn: staging
  displayName: development
  jobs:
  - template: job-apim-api-deploy.yml
    parameters:
      environment: development
      apiName: ${{ parameters.apiName }}
      parameterFileName: ${{ parameters.parameterFileName }}

- stage: systemtesting
  dependsOn: development
  displayName : System Testing
  jobs:
  - template: job-apim-api-deploy.yml
    parameters:
      environment: systemtesting
      apiName: ${{ parameters.apiName }}
      parameterFileName: ${{ parameters.parameterFileName }}
  