jobs:
- job: deployApim
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: AzureCLI@2
    displayName: Azure CLI
    inputs:
      azureSubscription: sp-apim-ado
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: $(System.DefaultWorkingDirectory)/pipeline/apim-template-deploy.sh
      arguments:
        -PWS-SYD-ARG-CICD
        -PetStoreV3
        -PWS-SYD-APIM-DEVCICD
        -$(System.DefaultWorkingDirectory)/api/PetStoreV3