trigger: none

parameters:
- name: apiName
  displayName: API Name
  type: string
  values:
  - Petstore

variables:
  - template: variables.yml

jobs:
- job: extractApim
  displayName: Extract APIM Template
  pool:
    vmImage: ubuntu-latest
  variables:
    - name: SOURCE_APIM
      value: ${{ variables.environments[0].apimName }}
    - name: DEST_APIM
      value: PWS-SYD-APIM-DEVCICD
    - name: API_NAME
      value: ${{ parameters.apiName }}
    - name: RESOURCE_GROUP
      value: ${{ variables.environments[0].resourceGroupName }}
    - name: TEMPLATE_DIRECTORY
      value: $(System.DefaultWorkingDirectory)/api/${{ parameters.apiName }}
    - name: SOURCE_BRANCH
      value: $(Build.SourceBranch)

  steps:
  - checkout: self
    persistCredentials: true
    
  - task: AzureCLI@2
    displayName: AZ CLI - Extract APIM Template
    inputs:
      azureSubscription: sp-apim-ado
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: $(System.DefaultWorkingDirectory)/pipeline/scripts/apim-template-extract.sh
