parameters:
- name: apiName
  displayName: API Name
  type: string
  values:
  - PetStoreV3

jobs:
- job: deployApim
  pool:
    vmImage: ubuntu-16.04
  variables:
    - name: DEST_APIM
      value: PWS-SYD-APIM-DEVCICD
    - name: API_NAME
      value: ${{ parameters.apiName }}
    - name: RESOURCE_GROUP
      value: PWS-SYD-ARG-CICD
    - name: TEMPLATE_DIRECTORY
      value: $(System.DefaultWorkingDirectory)/api/PetStoreV3

  steps:
  - task: AzureCLI@2
    displayName: APIM Template Extract
    inputs:
      azureSubscription: sp-apim-ado
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: $(System.DefaultWorkingDirectory)/pipeline/apim-template-extract.sh