SOURCEAPIM="PWS-SYD-APIM-CICD"
RESOURCEGROUP="PWS-SYD-ARG-CICD"
APINAME="petstore"
DESTAPIM="PWS-SYD-ARG-DEVCICD"
OUTDIR="/workspaces/apim-devops/api/petstore"
./apim-devops-tool.sh $SOURCEAPIM $RESOURCEGROUP $APINAME $DESTAPIM $OUTDIR