#!/bin/bash

SOURCEAPIM="PWS-SYD-APIM-CICD"
RESOURCEGROUP="PWS-SYD-ARG-CICD"
APINAME="PetStoreV3"
DESTAPIM="PWS-SYD-DEV-ARG-CICD"
echo "run script"
source apim-devops-tool.sh $SOURCEAPIM $RESOURCEGROUP $APINAME $DESTAPIM