variables:
  apiName: Petstore
  paramFile: Petstore-parameters.json

stages:
  - template: templates/stage-apim-api-deploy.yaml
    parameters:
      sitParameterFileName: $(paramFile)
      devParameterFileName: $(paramFile)
      apiName: $(apiName)
      templatePath: $(apiName)-$(Build.BuildId)