parameters:
  - name: salutation
    type: string
jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: ShellScript@2
        inputs:
          scriptPath: extract-test/run.sh
          args: ${{ parameters.salutation }}