parameters:
  - name: salutation
    type: string

resources:
  repositories:
    - repository: templates
      type: github
      name: mrsmitty/apim-devops
      ref: refs/heads/users/ps/extends
      endpoint: Integration

jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: templates
        path: $(Agent.BuildDirectory)/tools
      - task: ShellScript@2
        inputs:
          scriptPath: $(Agent.BuildDirectory)/tools//extract-test/run.sh
          args: ${{ parameters.salutation }}