trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      name: mrsmitty/apim-devops
      ref: refs/heads/users/ps/extends
      endpoint: Integration

variables:
  apiName: Petstore
  paramFile: Petstore-parameters.json

extends:
  template: pipeline/templates/stage-apim-api-deploy.yaml@templates
  parameters:
    sitParameterFileName: $(paramFile)
    devParameterFileName: $(paramFile)
    apiName: $(apiName)
    templatePath: $(apiName)-$(Build.BuildId)
